[package]
name = "dream-mover-rs"
version = "0.1.0"
edition = "2021"

[lib]
name = "dream_mover_rs"
crate-type = ["cdylib", "rlib"]

[dependencies]
sha2 = "0.10"
tokio = { version = "1", features = ["fs", "rt-multi-thread"] }
sysinfo = "0.30"
