name: Site CI

on:
  push:
    branches:
      - main
      - 'feat/**'
      - 'fix/**'
      - 'chore/**'
      - 'perf/**'
      - 'refactor/**'
    paths:
      - 'src/**'
      - 'public/**'
      - 'api/**'
      - 'vercel.json'
      - 'package.json'
      - 'pnpm-lock.yaml'
      - 'vite.config.*'
      - 'tailwind.config.*'
      - '.github/workflows/**'
  pull_request:
    branches:
      - '**'
    paths:
      - 'src/**'
      - 'public/**'
      - 'api/**'
      - 'vercel.json'
      - 'package.json'
      - 'pnpm-lock.yaml'
      - 'vite.config.*'
      - 'tailwind.config.*'
      - '.github/workflows/**'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: [20.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Enable Corepack
        run: corepack enable

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Check versions
        run: |
          pnpm -v
          node -v

      - name: Build (Vite)
        run: pnpm build