name: Site CI

on:
  push:
    branches: [main, 'feat/**', 'fix/**', 'chore/**', 'perf/**', 'refactor/**']
    paths:
      - 'src/**'
      - 'public/**'
      - 'server/**'
      - 'next.config.*'
      - 'vite.config.*'
      - 'postcss.config.cjs'
      - 'vercel.json'
      - 'package.json'
      - 'pnpm-lock.yaml'
      - 'tailwind.config.*'
      - '.github/workflows/**'
  pull_request:
    branches: ['**']
    paths:
      - 'src/**'
      - 'public/**'
      - 'server/**'
      - 'next.config.*'
      - 'vite.config.*'
      - 'postcss.config.cjs'
      - 'vercel.json'
      - 'package.json'
      - 'pnpm-lock.yaml'
      - 'tailwind.config.*'
      - '.github/workflows/**'

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  quick-lint:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955
      - uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061
        with:
          version: 10
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020
        with:
          node-version: '20.19.1'
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml
      - run: pnpm install --frozen-lockfile
      - name: Run QA ritual (non-blocking)
        run: pnpm run -s ritual:qa || true
      - name: Lint (if present)
        run: pnpm run -s lint --if-present

  build:
    needs: quick-lint
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955
      - uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061
        with:
          version: 10
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020
        with:
          node-version: '20.19.1'
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml
      - name: Restore Next cache (salted)
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830
        with:
          path: |
            .next/cache
          key: next-${{ runner.os }}-${{ github.run_id }}-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            next-${{ runner.os }}-
      - run: pnpm install --frozen-lockfile
      - name: Verify environment
        run: |
          echo "SHA from env: $GITHUB_SHA"
          git rev-parse HEAD
          node -v
          pnpm -v
          node -e "const fs=require('fs');const p=JSON.parse(fs.readFileSync('package.json','utf8'));console.log('build script:',p.scripts&&p.scripts.build)"
          pnpm ls sonner || true
      - name: Build (Next)
        run: pnpm build
